title: GUAC
description: The site for everyone's favorite software supply chain knowledge graph
logo: "/assets/images/guac.png"
favicon_ico: "/assets/images/favicon.ico"

ga_tracking: G-C1KPW2NZX2

aux_links:
  "GUAC on GitHub": "https://github.com/guacsec/guac"
  "GUAC Website": "https://guac.sh"

baseurl: "/guac-docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  guacsec
heading_anchors: true

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

color_scheme: better_contrast
markdown: kramdown

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 GUAC a Series of LF Projects, LLC. For web site terms of use, trademark policy and other project policies please see <a href=\"https://lfprojects.org/\">https://lfprojects.org/</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


